<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net48</TargetFramework>
        <LangVersion>latest</LangVersion>
        <Nullable>disable</Nullable>
        <AssemblyName>ProbeRoulette</AssemblyName>
        <Version>0.3.0</Version>
        <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
        <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
        <DebugType>portable</DebugType>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <Deterministic>true</Deterministic>
        <PathMap>$(MSBuildProjectDirectory)=/src/ProbeRoulette</PathMap>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net48" Version="1.0.3" PrivateAssets="all"/>
        <PackageReference Include="OWML" Version="2.16.3"/>
        <PackageReference Include="OuterWildsGameLibs" Version="1.1.16.1372"/>
        <None Update="manifest.json" CopyToOutputDirectory="PreserveNewest"/>
        <None Update="default-config.json" CopyToOutputDirectory="PreserveNewest"/>
    </ItemGroup>
</Project>
